// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chatroom struct {
	ID             string `json:"id"`
	Owneremail     string `json:"owneremail"`
	Recipientemail string `json:"recipientemail"`
	User           *User  `json:"user"`
}

type Comment struct {
	ID      string   `json:"id"`
	Comment string   `json:"comment"`
	Userid  int      `json:"userid"`
	Postid  int      `json:"postid"`
	Reply   []*Reply `json:"reply"`
	User    []*User  `json:"user"`
}

type Commentlike struct {
	ID        string `json:"id"`
	Commentid int    `json:"commentid"`
	Useremail string `json:"useremail"`
}

type Follower struct {
	ID         string `json:"id"`
	Userid     int    `json:"userid"`
	Followerid int    `json:"followerid"`
}

type Image struct {
	ID        string `json:"id"`
	Postid    int    `json:"postid"`
	Imagelink string `json:"imagelink"`
}

type Like struct {
	ID        string `json:"id"`
	Postid    int    `json:"postid"`
	Useremail string `json:"useremail"`
}

type Message struct {
	ID        string  `json:"id"`
	Toemail   string  `json:"toemail"`
	Fromemail string  `json:"fromemail"`
	Created   string  `json:"created"`
	Touser    *User   `json:"touser"`
	Fromuser  *User   `json:"fromuser"`
	Message   string  `json:"message"`
	Image     *string `json:"image"`
	Video     *string `json:"video"`
}

type Post struct {
	ID      string     `json:"id"`
	Caption string     `json:"caption"`
	Image   []*Image   `json:"image"`
	Video   *string    `json:"video"`
	Like    *int       `json:"like"`
	Userid  int        `json:"userid"`
	Comment []*Comment `json:"comment"`
	Created string     `json:"created"`
	User    *User      `json:"user"`
}

type Reply struct {
	ID        string `json:"id"`
	Commentid int    `json:"commentid"`
	Useremail string `json:"useremail"`
	Comment   string `json:"comment"`
	User      *User  `json:"user"`
}

type Save struct {
	ID        string `json:"id"`
	Postid    int    `json:"postid"`
	Useremail string `json:"useremail"`
}

type Searchhistory struct {
	ID    string `json:"id"`
	Word  string `json:"word"`
	Email string `json:"email"`
}

type Story struct {
	ID      string  `json:"id"`
	Userid  int     `json:"userid"`
	User    *User   `json:"user"`
	Created *string `json:"created"`
	Image   *string `json:"image"`
	Video   *string `json:"video"`
}

type User struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Username  string   `json:"username"`
	Bio       *string  `json:"bio"`
	Email     string   `json:"email"`
	Password  string   `json:"password"`
	Posts     []*Post  `json:"posts"`
	Follower  []*User  `json:"follower"`
	Following []*User  `json:"following"`
	Story     []*Story `json:"story"`
	Verified  *bool    `json:"verified"`
	Google    *bool    `json:"google"`
	Token     *string  `json:"token"`
}

type Viewedstory struct {
	ID        string `json:"id"`
	Storyid   int    `json:"storyid"`
	Viewed    string `json:"viewed"`
	Useremail string `json:"useremail"`
}
