CREATE TABLE comments
(
    id       BIGSERIAL PRIMARY KEY,
    comment VARCHAR(255) NOT NULL,
    userid BIGSERIAL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    postid BIGSERIAL REFERENCES posts (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)