CREATE TABLE posts(
    id BIGSERIAL PRIMARY KEY,
    caption VARCHAR(255) NOT NULL,
    video VARCHAR(255) NOT NULL,
    "like" INT NOT NULL,
    userid BIGSERIAL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    created VARCHAR(255) NOT NULL
)
