CREATE TABLE stories
(
    id BIGSERIAL PRIMARY KEY,
    userid BIGSERIAL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    created VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    video VARCHAR(255) NOT NULL
)
